import { v4 as uuidv4 } from "uuid";

const gallery = {
  gallery: {
    id: uuidv4(),
    component: "gallery/DefaultGallery/DefaultGallery",
    state: {
      name: "default-gallery",
      title: "Our Work",
      content: "Browse through our collection of stunning images",
      gallery: [
        {
          id: uuidv4(),
          title: "Project",
          col: 4,
          img: {
            src: "https://images.unsplash.com/photo-1456926631375-92c8ce872def?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wyMTc4NTl8MHwxfHNlYXJjaHw4fHxhbmltYWxzfGVufDB8fHx8MTcxMTIzNTUxOXww&ixlib=rb-4.0.3&q=80&w=400",
            width: "100%",
            height: "300px",
            alt: "service alt",
            hasOverlay: false,
            color: "",
          },
        },
        {
          id: uuidv4(),
          title: "Project",
          col: 4,
          img: {
            src: "https://images.unsplash.com/photo-1484406566174-9da000fda645?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wyMTc4NTl8MHwxfHNlYXJjaHwxMHx8YW5pbWFsc3xlbnwwfHx8fDE3MTEyMzU1MTl8MA&ixlib=rb-4.0.3&q=80&w=400",
            width: "100%",
            height: "300px",
            alt: "service alt",
            hasOverlay: false,
            color: "",
          },
        },
        {
          id: uuidv4(),
          title: "Project",
          col: 4,
          img: {
            src: "https://images.unsplash.com/photo-1629812456605-4a044aa38fbc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wyMTc4NTl8MHwxfHNlYXJjaHwyMHx8YW5pbWFsc3xlbnwwfHx8fDE3MTEyMzU1MTl8MA&ixlib=rb-4.0.3&q=80&w=400",
            width: "100%",
            height: "300px",
            alt: "service alt",
            hasOverlay: false,
            color: "",
          },
        },
        {
          id: uuidv4(),
          title: "Project",
          col: 4,
          img: {
            src: "https://images.unsplash.com/photo-1489084917528-a57e68a79a1e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wyMTc4NTl8MHwxfHNlYXJjaHwyNnx8YW5pbWFsc3xlbnwwfHx8fDE3MTEyMzU1MTl8MA&ixlib=rb-4.0.3&q=80&w=400",
            width: "100%",
            height: "300px",
            alt: "service alt",
            hasOverlay: false,
            color: "",
          },
        },
        {
          id: uuidv4(),
          title: "Project",
          col: 4,
          img: {
            src: "https://images.unsplash.com/photo-1574870111867-089730e5a72b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wyMTc4NTl8MHwxfHNlYXJjaHw2fHxhbmltYWxzfGVufDB8fHx8MTcxMTIzNTUxOXww&ixlib=rb-4.0.3&q=80&w=400",
            width: "100%",
            height: "300px",
            alt: "service alt",
            hasOverlay: false,
            color: "",
          },
        },
        {
          id: uuidv4(),
          title: "Project",
          col: 4,
          img: {
            src: "https://images.unsplash.com/photo-1543260775-945c562403b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wyMTc4NTl8MHwxfHNlYXJjaHwyOHx8YW5pbWFsc3xlbnwwfHx8fDE3MTEyMzU1MTl8MA&ixlib=rb-4.0.3&q=80&w=400",
            width: "100%",
            height: "300px",
            alt: "service alt",
            hasOverlay: false,
            color: "",
          },
        },
      ],
    },
  },
  gallery2: {
    id: uuidv4(),
    component: "gallery/DefaultGallery/DefaultGallery",
    state: {
      name: "default-gallery",
      title: "Our Work",
      content: "Browse through our collection of stunning images",
      gallery: [
        {
          id: uuidv4(),
          title: "Project",
          col: 6,
          img: {
            src: "https://images.unsplash.com/photo-1456926631375-92c8ce872def?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wyMTc4NTl8MHwxfHNlYXJjaHw4fHxhbmltYWxzfGVufDB8fHx8MTcxMTIzNTUxOXww&ixlib=rb-4.0.3&q=80&w=400",
            width: "100%",
            height: "300px",
            alt: "service alt",
            hasOverlay: false,
            color: "",
          },
        },
        {
          id: uuidv4(),
          title: "Project",
          col: 6,
          img: {
            src: "https://images.unsplash.com/photo-1484406566174-9da000fda645?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wyMTc4NTl8MHwxfHNlYXJjaHwxMHx8YW5pbWFsc3xlbnwwfHx8fDE3MTEyMzU1MTl8MA&ixlib=rb-4.0.3&q=80&w=400",
            width: "100%",
            height: "300px",
            alt: "service alt",
            hasOverlay: false,
            color: "",
          },
        },
        {
          id: uuidv4(),
          title: "Project",
          col: 6,
          img: {
            src: "https://images.unsplash.com/photo-1629812456605-4a044aa38fbc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wyMTc4NTl8MHwxfHNlYXJjaHwyMHx8YW5pbWFsc3xlbnwwfHx8fDE3MTEyMzU1MTl8MA&ixlib=rb-4.0.3&q=80&w=400",
            width: "100%",
            height: "300px",
            alt: "service alt",
            hasOverlay: false,
            color: "",
          },
        },
        {
          id: uuidv4(),
          title: "Project",
          col: 6,
          img: {
            src: "https://images.unsplash.com/photo-1489084917528-a57e68a79a1e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wyMTc4NTl8MHwxfHNlYXJjaHwyNnx8YW5pbWFsc3xlbnwwfHx8fDE3MTEyMzU1MTl8MA&ixlib=rb-4.0.3&q=80&w=400",
            width: "100%",
            height: "300px",
            alt: "service alt",
            hasOverlay: false,
            color: "",
          },
        },
        {
          id: uuidv4(),
          title: "Project",
          col: 6,
          img: {
            src: "https://images.unsplash.com/photo-1574870111867-089730e5a72b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wyMTc4NTl8MHwxfHNlYXJjaHw2fHxhbmltYWxzfGVufDB8fHx8MTcxMTIzNTUxOXww&ixlib=rb-4.0.3&q=80&w=400",
            width: "100%",
            height: "300px",
            alt: "service alt",
            hasOverlay: false,
            color: "",
          },
        },
        {
          id: uuidv4(),
          title: "Project",
          col: 6,
          img: {
            src: "https://images.unsplash.com/photo-1543260775-945c562403b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wyMTc4NTl8MHwxfHNlYXJjaHwyOHx8YW5pbWFsc3xlbnwwfHx8fDE3MTEyMzU1MTl8MA&ixlib=rb-4.0.3&q=80&w=400",
            width: "100%",
            height: "300px",
            alt: "service alt",
            hasOverlay: false,
            color: "",
          },
        },
      ],
    },
  },
  gallery3: {
    id: uuidv4(),
    component: "gallery/DefaultGallery/DefaultGallery",
    state: {
      name: "default-gallery",
      title: "Our Work",
      content: "Browse through our collection of stunning images",
      gallery: [
        {
          id: uuidv4(),
          title: "Project",
          col: 3,
          img: {
            src: "https://images.unsplash.com/photo-1456926631375-92c8ce872def?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wyMTc4NTl8MHwxfHNlYXJjaHw4fHxhbmltYWxzfGVufDB8fHx8MTcxMTIzNTUxOXww&ixlib=rb-4.0.3&q=80&w=400",
            width: "100%",
            height: "300px",
            alt: "service alt",
            hasOverlay: false,
            color: "",
          },
        },
        {
          id: uuidv4(),
          title: "Project",
          col: 3,
          img: {
            src: "https://images.unsplash.com/photo-1484406566174-9da000fda645?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wyMTc4NTl8MHwxfHNlYXJjaHwxMHx8YW5pbWFsc3xlbnwwfHx8fDE3MTEyMzU1MTl8MA&ixlib=rb-4.0.3&q=80&w=400",
            width: "100%",
            height: "300px",
            alt: "service alt",
            hasOverlay: false,
            color: "",
          },
        },
        {
          id: uuidv4(),
          title: "Project",
          col: 3,
          img: {
            src: "https://images.unsplash.com/photo-1629812456605-4a044aa38fbc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wyMTc4NTl8MHwxfHNlYXJjaHwyMHx8YW5pbWFsc3xlbnwwfHx8fDE3MTEyMzU1MTl8MA&ixlib=rb-4.0.3&q=80&w=400",
            width: "100%",
            height: "300px",
            alt: "service alt",
            hasOverlay: false,
            color: "",
          },
        },
        {
          id: uuidv4(),
          title: "Project",
          col: 3,
          img: {
            src: "https://images.unsplash.com/photo-1489084917528-a57e68a79a1e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wyMTc4NTl8MHwxfHNlYXJjaHwyNnx8YW5pbWFsc3xlbnwwfHx8fDE3MTEyMzU1MTl8MA&ixlib=rb-4.0.3&q=80&w=400",
            width: "100%",
            height: "300px",
            alt: "service alt",
            hasOverlay: false,
            color: "",
          },
        },
        {
          id: uuidv4(),
          title: "Project",
          col: 3,
          img: {
            src: "https://images.unsplash.com/photo-1574870111867-089730e5a72b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wyMTc4NTl8MHwxfHNlYXJjaHw2fHxhbmltYWxzfGVufDB8fHx8MTcxMTIzNTUxOXww&ixlib=rb-4.0.3&q=80&w=400",
            width: "100%",
            height: "300px",
            alt: "service alt",
            hasOverlay: false,
            color: "",
          },
        },
        {
          id: uuidv4(),
          title: "Project",
          col: 3,
          img: {
            src: "https://images.unsplash.com/photo-1543260775-945c562403b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wyMTc4NTl8MHwxfHNlYXJjaHwyOHx8YW5pbWFsc3xlbnwwfHx8fDE3MTEyMzU1MTl8MA&ixlib=rb-4.0.3&q=80&w=400",
            width: "100%",
            height: "300px",
            alt: "service alt",
            hasOverlay: false,
            color: "",
          },
        },
      ],
    },
  },
};
export default gallery;
